#!/usr/bin/env python3
import asyncio
import websockets
import argparse

# argparse


parser = argparse.ArgumentParser(description="Broadcast server.")
subparsers = parser.add_subparsers(dest="command", required=True)

# Create a specific sub-parser for the literal word "connect"
connect_parser = subparsers.add_parser("connect", help="Connects to the broadcast server.")

# Add the port argument specifically to the "connect" command
connect_parser.add_argument("--port", type=int, required=True, help="Optional flag to specify what port to start server on.")

args = parser.parse_args()













async def send_messages(websocket):
    while True:
        message = await asyncio.to_thread(input)
        await websocket.send(message)

async def receive_messages(websocket):
    async for message in websocket:
        print(f"{message}")


async def communicate():
    uri = f"ws://localhost:{args.port}"
    
    # async with automatically closes the connection when the block ends
    async with websockets.connect(uri) as websocket:
        print("Connected to server.")


        await asyncio.gather(
            send_messages(websocket),
            receive_messages(websocket)
        )


        # while True:
        #     try:
        #         message = input("You: ")


        #         # Send data to the server
        #         await websocket.send(message)

        #         # Wait for the server's reply
        #         response = await websocket.recv()
        #         # print(f"{message} ✅")
        #         print(response)
        #     except websockets.ConnectionClosed:
        #         print("Connection lost...")
        #         break
        #     except KeyboardInterrupt:
        #         print("\nYou left the chat...")
        #         break


if __name__ == "__main__":
    if args.command == "connect":
        asyncio.run(communicate())