#!/usr/bin/env python3
import asyncio
import websockets
import argparse

# argparse

parser = argparse.ArgumentParser(description="Broadcast server.")

parser.add_argument("start", help="Starts the broadcast server.")

args = parser.parse_args()









# websockets




# Starts websockets server with websockets.serve(handler, host, port)
async def main():
    # Declare a connected clients list
    connected_clients = []


    # Define handler function
    # Note: the handler is a function that defines how the server interacts with a connected client
    async def my_function(websocket):
        connected_clients.append(websocket)
        print(websocket)
  

        #try finally block that handles connected clients and handles client disconnection
        try:
            async for message in websocket:
                print("Received:", message)

                await websocket.send(f"Echo: {message}")

        finally:
            disconnected_client = websocket
            connected_clients.remove(websocket)
            print(f"Client {disconnected_client} disconnected...")


    # Start the server on localhost, port 8765
    async with websockets.serve(my_function, "localhost", 8765):
        print("Server started at ws://localhost:8765")
        await asyncio.Future()  # Run forever


if __name__ == "__main__":
    if args.start:
        asyncio.run(main())