#!/usr/bin/env python3
import asyncio
import websockets
import argparse
import uuid

# argparse

parser = argparse.ArgumentParser(description="Broadcast server.")
subparsers = parser.add_subparsers(dest="command", required=True)

# Create a specific sub-parser for the literal word "start"
start_parser = subparsers.add_parser("start", help="Starts the broadcast server.")

# Add the port argument specifically to the "start" command
start_parser.add_argument("--port", type=int, default=6767, help="Optional flag to specify what port to start server on.")

args = parser.parse_args()






# websockets



# Starts websockets server with websockets.serve(handler, host, port)
async def main():
    # Declare a connected clients list
    connected_clients = []


    # Define handler function
    # Note: the handler is a function that defines how the server interacts with a connected client
    async def my_function(websocket):
        connected_clients.append(websocket)
        #print(websocket)
  

        #try finally block that handles connected clients and handles client disconnection
        try:
            async for message in websocket:
                print("Received:", message)

                for client in connected_clients:
                    if client == websocket:
                        await client.send("✅")
                    else:
                        await client.send(f"{client}: {message}")

        finally:
            disconnected_client = websocket
            connected_clients.remove(websocket)
            print(f"Client {disconnected_client} disconnected...")


    # Start the server on localhost
    async with websockets.serve(my_function, "localhost", args.port):
        print(f"Server started at ws://localhost:{args.port}")
        await asyncio.Future()  # Run forever


if __name__ == "__main__":
    # if args.command == "start":
    #     asyncio.run(main())

    try:
        while True:
            if args.command == "start":
                asyncio.run(main())
    except KeyboardInterrupt:
        print("\nServer shutting down...")